### ISSUE TITLE
Update application concurrency check failed

### ISSUE THREAD

**Issue by Mrmantou** [TecMeet/tecmeet-openiddict-linq2db#1]
The concurrency check during update application in OpenIddictLinqToDBApplicationStore should use Applications, but not Tokens.
https://github.com/TecMeet/tecmeet-openiddict-linq2db/blob/master/src/TecMeet.OpenIddict.LinqToDB/Stores/OpenIddictLinqToDBApplicationStore.cs#L915

**Comment by timbze** [comment]
Fixed by #2
